import sys

for script_name in sys.argv[1:]:
    base_name = script_name.split('.')[0]
    print 'creating arc_%s.py' % base_name
    arc_script = open("arc_%s.py" % base_name,'w')
    arc_script.write("#This script automatically generated by create_arc_scripts.py\n")
    arc_script.write("import subprocess\n")
    arc_script.write("import os\n")
    arc_script.write("os.chdir('invest-3')\n")
    arc_script.write("subprocess.check_call('%s.exe')\n" % base_name)

